task: attetion-vad
pretrained_model_path: '{model}'
device: '{device}'
output_dir: '{output}'
data:
  dataset_path: '{dataset}'
  test_split: test
  batch_size: 1
  num_workers: 0
  max_test_samples: 1
